baseURL = "https://www.minimalistprogrammer.io/"
disqusShortname = "dayshardwood"
languageCode = "en-us"
theme = "minimal"
title = "Day's Hardwood"
[params]
author = "Kevin Guay"
subtitle = "Day's Hardwood"
